---
openapi: "3.0.0"
info:
  title: "UFC Fighter API"
  version: "1.0.0"
  contact:
    name: "Kevin Kirsche"
    url: "https://github.com/kkirsche/openapi-demo/issues"
servers:
  - url: "http://127.0.0.1:5000/api/v1"
    description: "Development server"
tags:
  - name: "Fighters"
paths:
  /fighters:
    summary: "Interact with figher data"
    get:
      tags:
        - "Fighters"
      summary: "List all championship UFC fighters"
      operationId: "ListAllFighters"
      responses:
        "200":
          description: "A list of all championship UFC fighters"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fighters"
components:
  schemas:
    Fighters:
      type: "array"
      items:
        $ref: "#/components/schemas/Fighter"
    Fighter:
      type: "object"
      required:
        - "id"
        - "name"
        - "weightclass"
      properties:
        id:
          type: "integer"
          format: "int64"
          minimum: 1
        name:
          type: "string"
        weightclass:
          type: "string"
      example:
        id: 1
        name: Daniel Cormier
        weightclass: "Heavyweight (Up to 265 pounds)"
